.TH SHA3SUM "1" "March 2019" "Jim McDevitt, MHI, Ltd." "User Commands"
.SH NAME
.B sha3sum
NIST SHA3 (Keccak) hash function utility
.SH SYNOPSIS
.B sha3sum
[\fIOPTIONS\fR] \fIfile1\fR \fIfile2\fR... [ [\fIOPTIONS\fR] \fIfile3\fR \fIfile4\fR... ]...
.SH DESCRIPTION
This manual page documents the MHI version of
.BR sha3sum .
.B sha3sum
hashes or encrypts files using the NIST SHA3 standard (FIPS 202), or
any other configuration with user specified parameters.
Files of random data may also be created of any size with any parameters.
.B sha3sum
utilizes both the duplex and sponge constructions with a state size of 1600.
Every parameter is configurable including the number of rounds
if the reference implementation is used.
.B sha3sum
can also generate a fingerprint for any file generated or encrypted.
Various options useful for testing are available as well.
.P
.B sha3sum
uses the Keccak sponge function to hash files with any valid
setting of rate (\fI\-r\fR), capacity (\fI\-C\fR), and
delimiter(\fI\-D\fR) with a facility (\fI\-c\fR) to detect if any file
previously hashed has changed.
.P
.B sha3sum
as a stream cipher, can encrypt (\fI\+q\fR or \fI\+Q\fR) or decrypt
(\fI\-q\fR or \fI\-Q\fR) files using two different modes of operation.
.SH OPTIONS
.pp
(option letters are case-sensitive and processed in order given)
.TP
\fB\-bn\fR
Hash a dummy file of length\fB\ n\fR bits.
.TP
\fB\-Bn\fR
Hash a dummy file of length\fB\ n\fR bytes.
.TP
\fB\-c xxxx\fR
Check hash from file
.B xxxx
to see if they are still valid.
Here
.B xxxx
is saved output from a previous run of sha3sum.
Names of files whose hash value have changed are printed.
.TP
\fB\-dn\fR
Set digest length to\fB\ n\fR bits, 8<=\fB\ n\fR
<=r (rate); default is 256. See also \fI\-L\fR.
.TP
\fB\-Dxx\fR
Set delimited suffix to
.B xx
(hexadecimal), 01<=
.B xx
<=ff;
default is 06 (hex).
.TP
\fB\-en\fR
Print\fB\ n\fR (optional) blocks of output \fI\-L\fR bits in size.
Used for arbitrary length output,\fB\ n\fR > 0; default is 1.
If this option is not present and \fI\-L\fR is, \fI\-e1\fR assumed.
.TP
\fB\+/-f xxxx\fR
Output is to file
.B xxxx
binary or ASCII hex. Used with \fI\-L\fR
and \fI\-e\fR. \fI\-f\fR is in squeeze mode, \fI\+f\fR is in duplex mode.
Output is then generated from a key, key file,
IV, IV file, and/or a random seed.
.TP
\fB\-gn\fR
If\fB\ n\fR (optional) = 0, a binary file is produced (default);
if\fB\ n\fR = 1, an ASCII hex file is created. Used with \fI\-L\fR and
\fI\-f\fR.  See also option \fI\-e\fR.
.TP
\fB\-h\fR
Print this help information.
.TP
\fB\-in\fR
Print level\fB\ n\fR intermediate values (\fB\ n\fR optional)
1<=\fB\ n\fR <=3; default is 1.
.TP
\fB\-jxxyy\fR
Set IV to hexadecimal
.B xxyy..
(length 1 to 8192 bits);
.TP
\fB\-Jxxxx\fR
Set IV to ascii
.B xxxx
(length 1 to 1024 bytes);
.TP
\fB\-kxxxx\fR
Set key to ascii
.B xxxx
(length 0 to 64 bytes);
.B xxxx
optional.
.TP
\fB\-Kxxxx\fR
Set key to ascii
.B xxxx
(length 0 to 64 bytes);
.B xxxx
optional.
.TP
\fB\-ln\fR
Use\fB\ n\fR bits (0 <=\fB\ n\fR <= 8192) for the message size given with
the \fI\-m\fR option.
.TP
\fB\-Ln\fR
Output\fB\ n\fR bits per squeeze (1 <=\fB\ n\fR <= 16384); default is 8192.
Arbitrary length output. See also option \fI\-e\fR.
.TP
\fB\-mxxxx\fR
Compute hash of hexadecimal message
.B xxxx\fR;
.B xxxx
optional.
.TP
\fB\-Mxxxx\fR
Compute hash of ASCII message
.B xxxx\fR;
.B xxxx
optional.
.TP
\fB\-nc\fR
Configures all settings based on capacity.  If\fB\ c\fR is the capacity,
then\fB\ d\fR =\fB\ c\fR/2,\fB\ r\fR = 1600 -\fB\ c\fR, \fB\ D\fR = 06 (hex),\fB\ s\fR =\fB\ c\fR/2.
.TP
\fB\-Nn\fR
Configures all settings based on the following table
where\fB\ n\fR is the preset #,\fB\ d\fR is the digest size,\fB\ r\fR is the
rate,\fB\ C\fR is the capacity, and\fB\ D\fR is the delimiter.
.br

\fB\ n\fR  \fB\ d\fR   \fB\ r\fR   \fB\ C\fR  \fB\ D\fR  Designator Strength
.br
=========================================
.br
 0 256 1088  512  06  Default   \fB\ s\fR >= 128 SHA3-256
.br
 1 128 1344  256  1f  SHAKE128  \fB\ s\fR <= 128 VLO
.br
 2 224 1152  448  06  SHA3-224  \fB\ s\fR >= 112 
.br
 3 256 1088  512  1f  SHAKE256  \fB\ s\fR <= 256 VLO
.br
 4 256 1088  512  06  SHA3-256  \fB\ s\fR >= 128 
.br
 5 256 1024  576  01  Keccak    \fB\ s\fR >= 128 
.br
 6 384  832  768  06  SHA3-384  \fB\ s\fR >= 192 
.br
 7 512  576 1024  06  SHA3-512  \fB\ s\fR >= 256 
.br
=========================================
.br
 VLO denotes variable length output.
.TP
\fB\-on\fR
Slow\fB\ n\fR-bit one-way function.  Update state with\fB\ n\fR
0 bits before the state is finalized.
.TP
\fB\-On\fR
Slow\fB\ n\fR-byte one-way function.  Update state with\fB\ n\fR
0 bytes before the state is finalized.
.TP
\fB\-p\fR
Print input parameters.
.TP
\fB\+/-q \fIinfile\fR \fIoutfile\fR
Stream cipher. Apply key stream to file \fIinfile\fR,
and write the result to file \fIoutfile\fR.  \fI+q\fR encrypts,
\fI-q\fR decrypts.  A key and/or IV may be used.
.TP
\fB\+/-Q \fIinfile\fR \fIoutfile\fR
Stream cipher. Apply key stream to file \fIinfile\fR,
and write the result to file \fIoutfile\fR.  \fI+Q\fR encrypts,
\fI-Q\fR decrypts. Unlike \fI-q\fR, this uses the duplex construct.
Required input is a key. An IV may be specified. The stream
is re-seeded every\fB\ r\fR/8 - 1 bytes.
If no IV is specified, an IV will be generated.
.TP
\fB\-rn\fR
Set rate to\fB\ n\fR (16<=\fB\ n\fR <=1600); default is 1088.
Also sets\fB\ C\fR (capacity) to 1600 -\fB\ r\fR (rate).
.TP
\fB\-Rn\fR
Set rounds to\fB\ n\fR (1<=\fB\ n\fR <=72); default is 24.
.TP
\fB\-sn\fR
Measure time to perform\fB\ n\fR initializations (\fB\ n\fR optional)
on any provided configuration;\fB\ n\fR defaults to one.
.TP
\fb\-S\fR
Allow the key to be printed. This is used by options -c
and -p. Should only be used for testing purposes or if
the key is used for non-security purposes such as a salt.
The key printed is specified by -K.
.TP
\fB\-t\fR
Turn on printing of elapsed times and bytes/second
for each hash as well as the job total.
.TP
\fB\-T\fR
Turn on printing of elapsed times and bytes/second
for the job total only.
.TP
\fB\-u\fR
Generate and use a random seed of 1600 bits.  Useful
for generating key files and IV files.  Note that the use of
this option renders any operation non-reproducible.
.TP
\fB\-v\fR
Print program version information.
.TP
\fB\-x xxxx\fR
Use the first 512 bytes of file
.B xxxx
as a key file.  If \fI-k\fR or \fI-K\fR is also used,
the key and this file are combined.
.TP
\fB\-X xxxx\fR
Use the first 1024 bytes of file
.B xxxx
as an IV file.  If \fI-j\fR or \fI-J\fR is also used,
the IV and this file are combined.
.TP
\fB\-yn\fR
Set PIM to\fB\ n\fR (key iterations)
Default is 100000.
.PP
For each file given,
.B sha3sum
prints a line of the form: 
.br

    hashvalue filename
.br

If file is `-', or if no files are given, standard input is used.
.br
Integers\fB n\fR may use scientific notation, e.g. -B1e9 .
.SH AUTHOR
Written by Jim McDevitt.
.br 
The Keccak sponge function was designed and implemented by Guido
Bertoni, Joan Daemen, Michaël Peeters and Gilles Van Assche.
.SH COPYRIGHT
Copyright (c) 2012-2019 McDevitt Heavy Industries, Ltd. (MHI)
.br
                   All Rights Reserved.
.br

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, version 2.0 only.

There is NO WARRANTY, to the extent permitted by law.
